# Generated by Django 5.0.1 on 2024-05-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Account_Number',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Auto_Pay',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Bank_Account_Number',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Bank_Account_Type',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Bank_Name',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Bank_Routing_Number',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Password',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Payment_Mode',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Remmitance_Address',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Remmitance_City',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Remmitance_Country',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Remmitance_State',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Remmitance_Zip',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='URL',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Username',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ban_onboarding_payment',
            name='Vendor_Name',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Account_Number',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Auto_Pay',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Bank_Account_Number',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Bank_Account_Type',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Bank_Name',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Bank_Routing_Number',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Password',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Payment_Mode',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Remmitance_Address',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Remmitance_City',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Remmitance_Country',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Remmitance_State',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Remmitance_Zip',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='URL',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Username',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingdata',
            name='Vendor_Name',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
    ]
