# Generated by Django 5.0.1 on 2024-05-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_company_onbording_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban_onboarding_payment',
            name='Company',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ban_onboarding_payment',
            name='Sub_Company',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
    ]
