from django.db import models
class Column_mapping_data(models.Model):
    columns = models.CharField(max_length=1000)

class MappingData(models.Model):
    Account_Number = models.CharField(max_length=100, default='NA',null=True)
    Remmitance_Address = models.CharField(max_length=100, default='NA',null=True)
    Remmitance_City = models.CharField(max_length=100, default='NA',null=True)
    Remmitance_State = models.CharField(max_length=100, default='NA',null=True)
    Remmitance_Zip = models.CharField(max_length=100, default='NA',null=True)
    Remmitance_Country = models.CharField(max_length=100, default='NA',null=True)
    Payment_Mode = models.CharField(max_length=100, default='NA',null=True)
    URL = models.CharField(max_length=100, default='NA',null=True)
    Username = models.CharField(max_length=100, default='NA',null=True) 
    Password = models.CharField(max_length=100, default='NA',null=True)
    Vendor_Name = models.CharField(max_length=100, default='NA',null=True)
    Bank_Name = models.CharField(max_length=100, default='NA',null=True)
    Bank_Account_Number = models.CharField(max_length=100, default='NA',null=True)
    Bank_Routing_Number = models.CharField(max_length=100, default='NA',null=True)
    Bank_Account_Type = models.CharField(max_length=100, default='NA',null=True)
    Auto_Pay = models.CharField(max_length=100, default='NA',null=True)

class ban_onboarding_payment(models.Model):
    Account_Number = models.CharField(max_length=100, default='NA',null=True)
    Remmitance_Address = models.CharField(max_length=100, default='NA',null=True)
    Remmitance_City = models.CharField(max_length=100, default='NA',null=True)
    Remmitance_State = models.CharField(max_length=100, default='NA',null=True)
    Remmitance_Zip = models.CharField(max_length=100, default='NA',null=True)
    Remmitance_Country = models.CharField(max_length=100, default='NA',null=True)
    Payment_Mode = models.CharField(max_length=100, default='NA',null=True)
    URL = models.CharField(max_length=100, default='NA',null=True)
    Username = models.CharField(max_length=100, default='NA',null=True) 
    Password = models.CharField(max_length=100, default='NA',null=True)
    Vendor_Name = models.CharField(max_length=100, default='NA',null=True)
    Bank_Name = models.CharField(max_length=100, default='NA',null=True)
    Bank_Account_Number = models.CharField(max_length=100, default='NA',null=True)
    Bank_Routing_Number = models.CharField(max_length=100, default='NA',null=True)
    Bank_Account_Type = models.CharField(max_length=100, default='NA',null=True)
    Auto_Pay = models.CharField(max_length=100, default='NA',null=True)
